### ISSUE TITLE
[Request] sblocation to return GPS coordinates

### ISSUE THREAD

**Issue by frakman1** [awesomebing1/iOS-sbutils#4]
It woud be awesome if you could have a command like `sblocation` return the GPS coordinates of the phone.

**Comment by spotlightishere** [comment]
Hi - I'm in no active position to maintain this anymore, apologies.
You could most likely use CoreLocation (or interface with locationd by itself) to achieve this. It appears the domain of entitlements on `com.apple.locationd.*` might grant a few permissions that'd help as well.

Best of luck!
